[project]
name = "caf"
dynamic = ["version"]
description = "Content addressable file store command-line tool"
readme = "README.md"
authors = [
    {name = "James Saryerwinnie", email = "js@jamesls.com"}
]
license = "Apache-2.0"
keywords = ["caf"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Rust",
]
requires-python = ">=3.8"

[build-system]
requires = ["maturin>=1.13,<2.0"]
build-backend = "maturin"

[project.urls]
Homepage = "https://github.com/jamesls/caf"

[tool.maturin]
bindings = "bin"
manifest-path = "crates/caf/Cargo.toml"
locked = true
strip = true
