//! Store-level verification of the committed golden store fixture.
//!
//! `tests/golden/store` (repository root) is a real store generated by
//! the Python implementation: two chains of
//! 3 and 2 files. `caf-format` pins its format primitives; this test
//! runs the complete verifier against the fixture, including chains,
//! roots, orphans, and the metadata aggregate, serially and in
//! parallel.

use std::num::NonZeroUsize;
use std::path::{Path, PathBuf};

use caf_store::Verifier;

fn store_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden/store")
}

#[test]
fn golden_store_verifies_cleanly() {
    let report = Verifier::new(store_dir())
        .verify()
        .expect("verification runs");
    assert!(report.success(), "{:?}", report.diagnostics());
    assert_eq!(report.files_checked(), 5);
}

#[test]
fn golden_store_verifies_cleanly_in_parallel() {
    let report = Verifier::new(store_dir())
        .jobs(NonZeroUsize::new(4).expect("four workers"))
        .verify()
        .expect("verification runs");
    assert!(report.success(), "{:?}", report.diagnostics());
    assert_eq!(report.files_checked(), 5);
}
