//! Format-level checks of the committed golden store fixture.
//!
//! `tests/golden/store` (repository root) is a real store generated by the
//! Python implementation. Every data file in it
//! must satisfy the version 2 format rules through this crate: its path
//! encodes its digest, its header validates, and its content is exactly
//! the deterministic stream for its seed. Store-level verification
//! (chains, roots, and orphans) is outside this crate; this test pins the
//! format primitives against Python-produced bytes.

use std::collections::BTreeMap;
use std::io::Read;
use std::path::{Path, PathBuf};

use caf_format::{ContentReader, Digest, Hasher, Header, parse_hash_from_path};

fn store_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden/store")
}

/// Data files as `relative path -> file bytes`, sorted for determinism.
fn read_data_files() -> BTreeMap<PathBuf, Vec<u8>> {
    let store = store_dir();
    let mut files = BTreeMap::new();
    let mut pending = vec![store.clone()];
    while let Some(dir) = pending.pop() {
        for entry in std::fs::read_dir(&dir).expect("store fixture exists") {
            let entry = entry.expect("readable store entry");
            let path = entry.path();
            if path.file_name().is_some_and(|name| name == ".metadata") {
                continue;
            }
            if entry.file_type().expect("file type").is_dir() {
                pending.push(path);
            } else {
                let relative = path
                    .strip_prefix(&store)
                    .expect("entry is under the store root")
                    .to_path_buf();
                let bytes = std::fs::read(&path).expect("readable data file");
                files.insert(relative, bytes);
            }
        }
    }
    assert!(!files.is_empty(), "golden store fixture has data files");
    files
}

#[test]
fn every_data_file_satisfies_the_format() {
    for (relative, bytes) in &read_data_files() {
        let display = relative.display();

        let path_digest = parse_hash_from_path(relative)
            .unwrap_or_else(|err| panic!("{display}: not a CAF layout path ({err})"));

        let header = Header::parse(bytes).unwrap_or_else(|err| panic!("{display}: {err}"));
        assert_eq!(
            header.file_length(),
            bytes.len() as u64,
            "{display}: header length field",
        );

        assert_eq!(
            Digest::compute(bytes),
            path_digest,
            "{display}: whole-file digest",
        );

        let mut expected = Vec::with_capacity(bytes.len() - caf_format::HEADER_SIZE);
        ContentReader::new(header.content_seed())
            .take(header.content_length())
            .read_to_end(&mut expected)
            .expect("infinite stream");
        assert_eq!(
            &bytes[caf_format::HEADER_SIZE..],
            expected,
            "{display}: content stream",
        );
    }
}

#[test]
fn parent_links_resolve_within_the_store() {
    let files = read_data_files();
    let digests: Vec<Digest> = files
        .keys()
        .map(|relative| parse_hash_from_path(relative).expect("CAF layout path"))
        .collect();

    let mut roots = 0;
    for (relative, bytes) in &files {
        let header = Header::parse(bytes).expect("valid header");
        if header.is_root() {
            roots += 1;
        } else {
            assert!(
                digests.contains(&header.parent()),
                "{}: parent {} not in store",
                relative.display(),
                header.parent(),
            );
        }
    }
    // The fixture was generated as two chains (tests/golden/README.md).
    assert_eq!(roots, 2, "fixture has one root per chain");
}

#[test]
fn metadata_all_matches_the_root_markers() {
    let roots_dir = store_dir().join(".metadata").join("roots");
    let mut names: Vec<String> = std::fs::read_dir(&roots_dir)
        .expect("roots directory exists")
        .map(|entry| {
            entry
                .expect("readable roots entry")
                .file_name()
                .into_string()
                .expect("root marker names are ASCII hex")
        })
        .collect();
    names.sort_unstable();

    let mut hasher = Hasher::new();
    for name in &names {
        hasher.update(name.as_bytes());
    }

    let all =
        std::fs::read(store_dir().join(".metadata").join("all")).expect("metadata all file exists");
    assert_eq!(all, hasher.finalize().to_hex().into_bytes());
}
